# Generated by Django 4.0.10 on 2023-12-03 18:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('last_transaction_date', models.DateTimeField(blank=True, null=True)),
                ('last_save_date', models.DateTimeField(blank=True, null=True)),
                ('xirr', models.DecimalField(blank=True, decimal_places=10, max_digits=17, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('name', 'user')},
            },
        ),
        migrations.CreateModel(
            name='AccountHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ams.account')),
            ],
        ),
        migrations.CreateModel(
            name='Exchange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('mic', models.CharField(max_length=10)),
                ('country', models.CharField(blank=True, max_length=128, null=True)),
                ('code', models.CharField(max_length=20)),
                ('timezone', models.CharField(blank=True, max_length=100, null=True)),
                ('opening_hour', models.TimeField(blank=True, null=True)),
                ('closing_hour', models.TimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('deposit', 'Deposit'), ('withdrawal', 'Withdrawal'), ('buy', 'Buy'), ('sell', 'Sell'), ('dividend', 'dividend'), ('cost', 'cost')], max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=17)),
                ('currency', models.CharField(max_length=10)),
                ('date', models.DateTimeField()),
                ('correlation_id', models.IntegerField(blank=True, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='ams.account')),
            ],
        ),
        migrations.CreateModel(
            name='StockTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_id', models.IntegerField()),
                ('quantity', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=13)),
                ('transaction_type', models.CharField(choices=[('buy', 'Buy'), ('sell', 'Sell'), ('price', 'Price'), ('dividend', 'Dividend')], max_length=10)),
                ('date', models.DateTimeField()),
                ('pay_currency', models.CharField(blank=True, max_length=3, null=True)),
                ('exchange_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=13, null=True)),
                ('commission', models.DecimalField(blank=True, decimal_places=2, max_digits=13, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_transaction', to='ams.account')),
            ],
        ),
        migrations.CreateModel(
            name='StockBalanceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_id', models.IntegerField()),
                ('date', models.DateField()),
                ('quantity', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=13)),
                ('result', models.DecimalField(decimal_places=2, max_digits=13)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ams.account')),
            ],
        ),
        migrations.CreateModel(
            name='StockBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_id', models.IntegerField()),
                ('quantity', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=13)),
                ('result', models.DecimalField(decimal_places=2, max_digits=13)),
                ('last_save_date', models.DateField(null=True)),
                ('first_event_date', models.DateField(null=True)),
                ('last_transaction_date', models.DateTimeField(null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_balance', to='ams.account')),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isin', models.CharField(blank=True, max_length=12, null=True)),
                ('ticker', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=128)),
                ('currency', models.CharField(max_length=3)),
                ('type', models.CharField(choices=[('STOCK', 'Stock'), ('CRYPTO', 'Cryptocurrency')], default='STOCK', max_length=6)),
                ('exchange', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ams.exchange')),
            ],
        ),
        migrations.CreateModel(
            name='AccountPreferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_currency', models.CharField(max_length=3)),
                ('tax_currency', models.CharField(max_length=3)),
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='account_preferences', to='ams.account')),
            ],
        ),
        migrations.CreateModel(
            name='AccountHistoryBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(max_length=3)),
                ('account_history', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ams.accounthistory')),
            ],
        ),
        migrations.CreateModel(
            name='FavoriteAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50)),
                ('exchange', models.CharField(blank=True, max_length=50, null=True)),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=50)),
                ('country', models.CharField(blank=True, max_length=50, null=True)),
                ('currency', models.CharField(max_length=10)),
                ('isin', models.CharField(blank=True, max_length=20, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('code', 'exchange')},
            },
        ),
        migrations.CreateModel(
            name='AccountBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=17)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='balances', to='ams.account')),
            ],
            options={
                'unique_together': {('account', 'currency')},
            },
        ),
    ]
