# Generated by Django 4.0.10 on 2024-01-08 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ams', '0002_stockbalance_average_price'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Transaction',
            new_name='AccountTransaction',
        ),
        migrations.RenameModel(
            old_name='Stock',
            new_name='Asset',
        ),
        migrations.RenameModel(
            old_name='StockBalance',
            new_name='AssetBalance',
        ),
        migrations.RenameModel(
            old_name='StockBalanceHistory',
            new_name='AssetBalanceHistory',
        ),
        migrations.RenameModel(
            old_name='StockTransaction',
            new_name='AssetTransaction',
        ),
    ]
