# Generated by Django 4.0.10 on 2023-07-24 15:05

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ams', '0002_account'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='account',
            unique_together={('currency', 'user')},
        ),
    ]
