# Generated by Django 4.0.10 on 2023-09-14 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ams', '0003_account_last_save_date_account_last_transaction_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
