# Generated by Django 4.0.10 on 2023-08-04 13:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ams', '0005_transaction'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='account',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='account',
            name='name',
            field=models.CharField(default='ESSA', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='account',
            unique_together={('name', 'user')},
        ),
        migrations.RemoveField(
            model_name='account',
            name='balance',
        ),
        migrations.RemoveField(
            model_name='account',
            name='currency',
        ),
    ]
