# Generated by Django 4.0.10 on 2023-10-22 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ams', '0006_exchange_stocktransaction_stock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stocktransaction',
            name='currency',
        ),
        migrations.AddField(
            model_name='stock',
            name='currency',
            field=models.CharField(default='EUR', max_length=3),
            preserve_default=False,
        ),
    ]
