# Generated by Django 4.0.10 on 2023-10-24 17:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ams', '0007_remove_stocktransaction_currency_stock_currency'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isin', models.CharField(max_length=12)),
                ('quantity', models.IntegerField()),
                ('value', models.DecimalField(decimal_places=2, max_digits=13)),
                ('result', models.DecimalField(decimal_places=2, max_digits=13)),
                ('last_save_date', models.DateField(null=True)),
                ('first_event_date', models.DateField(null=True)),
                ('last_transaction_date', models.DateTimeField()),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_balance', to='ams.account')),
            ],
        ),
    ]
