# Generated by Django 4.0.10 on 2023-08-07 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ams', '0007_accountbalance_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='accountbalance',
            unique_together={('account', 'currency')},
        ),
    ]
