# Generated by Django 4.0.10 on 2023-10-27 11:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ams', '0008_stockbalance'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountPreferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_currency', models.CharField(max_length=3)),
                ('tax_value', models.DecimalField(decimal_places=2, max_digits=5)),
                ('tax_currency', models.CharField(max_length=3)),
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='account_preferences', to='ams.account')),
            ],
        ),
    ]
