# Generated by Django 4.0.10 on 2023-10-25 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ams', '0008_stockbalance'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exchange',
            old_name='closing_time',
            new_name='closing_hour',
        ),
        migrations.AddField(
            model_name='exchange',
            name='code',
            field=models.CharField(default=1234, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='exchange',
            name='country',
            field=models.CharField(default='abc', max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='exchange',
            name='mic',
            field=models.CharField(default='abc', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='exchange',
            name='opening_hour',
            field=models.TimeField(default='19:00:00'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='exchange',
            name='timezone',
            field=models.CharField(default='abc', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stock',
            name='ticker',
            field=models.CharField(default='abc', max_length=5),
            preserve_default=False,
        ),
    ]
