# Generated by Django 4.0.10 on 2023-09-13 18:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ams', '0008_alter_accountbalance_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exchange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='StockTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isin', models.CharField(max_length=12)),
                ('quantity', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=13)),
                ('transaction_type', models.CharField(choices=[('buy', 'Buy'), ('sell', 'Sell')], max_length=10)),
                ('currency', models.CharField(max_length=3)),
                ('date', models.DateTimeField()),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_transaction', to='ams.account')),
                ('exchange', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ams.exchange')),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('isin', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('exchange', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ams.exchange')),
            ],
        ),
    ]
