# Generated by Django 4.0.10 on 2023-10-30 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ams', '0009_accountpreferences'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accountpreferences',
            name='tax_value',
        ),
    ]
