# Generated by Django 4.0.10 on 2023-11-01 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ams', '0009_rename_closing_time_exchange_closing_hour_and_more'),
        ('ams', '0010_remove_accountpreferences_tax_value'),
    ]

    operations = [
    ]
