# Generated by Django 4.0.10 on 2023-11-02 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ams', '0011_merge_20231101_1957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stocktransaction',
            name='transaction_type',
            field=models.CharField(choices=[('buy', 'Buy'), ('sell', 'Sell'), ('price', 'Price')], max_length=10),
        ),
    ]
