# Generated by Django 4.0.10 on 2023-11-05 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ams', '0011_merge_20231101_1957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exchange',
            name='timezone',
            field=models.CharField(max_length=100),
        ),
    ]
