# Generated by Django 4.0.10 on 2023-11-05 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ams', '0012_alter_exchange_timezone'),
        ('ams', '0012_alter_stocktransaction_transaction_type'),
    ]

    operations = [
    ]
