# Generated by Django 4.0.10 on 2023-11-08 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ams', '0011_account_xirr'),
        ('ams', '0012_alter_stocktransaction_transaction_type'),
    ]

    operations = [
    ]
