# Generated by Django 4.0.10 on 2023-11-07 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ams', '0013_merge_20231105_1258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.CharField(choices=[('deposit', 'Deposit'), ('withdrawal', 'Withdrawal'), ('buy', 'Buy'), ('sell', 'Sell')], max_length=10),
        ),
    ]
