# Generated by Django 4.0.10 on 2023-11-08 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ams', '0013_merge_20231108_1646'),
        ('ams', '0014_alter_transaction_type'),
    ]

    operations = [
    ]
