# Generated by Django 4.0.10 on 2023-11-09 05:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ams', '0014_alter_transaction_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockbalance',
            name='last_transaction_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.CreateModel(
            name='StockBalanceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isin', models.CharField(max_length=12)),
                ('date', models.DateField()),
                ('quantity', models.IntegerField()),
                ('value', models.DecimalField(decimal_places=2, max_digits=13)),
                ('result', models.DecimalField(decimal_places=2, max_digits=13)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ams.account')),
            ],
        ),
    ]
