# Generated by Django 4.0.10 on 2023-11-11 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ams', '0015_alter_stockbalance_last_transaction_date_and_more'),
        ('ams', '0015_merge_20231108_2054'),
    ]

    operations = [
    ]
