# Generated by Django 4.0.10 on 2023-11-08 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ams', '0015_stockbalancehistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockbalance',
            name='last_transaction_date',
            field=models.DateTimeField(null=True),
        ),
    ]
