# Generated by Django 4.0.10 on 2023-11-16 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ams', '0016_merge_20231111_1709'),
    ]

    operations = [
        migrations.AddField(
            model_name='stocktransaction',
            name='exchange_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=13, null=True),
        ),
        migrations.AddField(
            model_name='stocktransaction',
            name='pay_currency',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
    ]
