# Generated by Django 4.0.10 on 2023-11-20 23:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ams', '0017_remove_stockbalance_value_and_more'),
        ('ams', '0017_stocktransaction_exchange_rate_and_more'),
    ]

    operations = [
    ]
