# Generated by Django 4.0.10 on 2023-11-25 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ams', '0018_merge_20231120_2310'),
    ]

    operations = [
        migrations.AddField(
            model_name='stocktransaction',
            name='commission',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='stocktransaction',
            name='transaction_type',
            field=models.CharField(choices=[('buy', 'Buy'), ('sell', 'Sell'), ('price', 'Price'), ('dividend', 'Dividend')], max_length=10),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.CharField(choices=[('deposit', 'Deposit'), ('withdrawal', 'Withdrawal'), ('buy', 'Buy'), ('sell', 'Sell'), ('dividend', 'dividend')], max_length=10),
        ),
    ]
