# Generated by Django 4.0.10 on 2023-11-27 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ams', '0019_stocktransaction_commission_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FavoriteAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50)),
                ('exchange', models.CharField(blank=True, max_length=50, null=True)),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=50)),
                ('country', models.CharField(blank=True, max_length=50, null=True)),
                ('currency', models.CharField(max_length=10)),
                ('isin', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'unique_together': {('code', 'exchange')},
            },
        ),
    ]
